steps:
- task: DownloadBuildArtifacts@1
  inputs:
    buildType: 'specific'
    project: CT Engineering School
    pipeline: Swagger-CI-JeraldinneMolleda
    specificBuildWithTriggering: false 
    buildVersionToDownload: 'latest' 
    allowPartiallySucceededBuilds: false 
    branchName: 'application/JeraldinneMolleda' 
    buildId: '373'
    #tags: # string. Optional. Use when buildType == specific && buildVersionToDownload != specific. Build Tags. 
    downloadType: 'single'
    artifactName: 'AzureTestProject'
    downloadPath: '$(System.DefaultWorkingDirectory)'
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure Subscription Academy'
    appType: 'webApp'
    appName: 'UWUDCTPJMWAP76'
    package: '$(System.DefaultWorkingDirectory)/AzureTestProject'
    deploymentMethod: 'auto'