steps:
- task: DownloadBuildArtifacts@1
  inputs:
    buildType: 'specific'
    project: CT Engineering School
    pipeline: Swagger-CI-JeraldinneMolleda
    specificBuildWithTriggering: false 
    buildVersionToDownload: 'latest' 
    allowPartiallySucceededBuilds: false 
    branchName: 'application/JeraldinneMolleda' 
    buildId: '373'
    #tags: # string. Optional. Use when buildType == specific && buildVersionToDownload != specific. Build Tags. 
    downloadType: 'single'
    artifactName: 'AzureTestProject'
    downloadPath: '$(System.DefaultWorkingDirectory)'

- task: PowerShell@2
  displayName: 'Generate name app service plan '
  inputs:
    targetType: filePath
    filePath: '$(System.DefaultWorkingDirectory)/_Swagger-CI-JeraldinneMolleda/AzureTestProject/scripts/generateName.ps1'
    arguments: '-Location "West US" -ResourceType "App Service Plan" -Environment "DEV"'
    workingDirectory: '$(System.DefaultWorkingDirectory)'

- task: AzurePowerShell@5
  displayName: 'Deploy resource app service plan copy'
  inputs:
    azureSubscription: 'Azure Subscription Academy'
    ScriptPath: '$(System.DefaultWorkingDirectory)/_Swagger-CI-JeraldinneMolleda/AzureTestProject/scripts/createResourceAzure.ps1'
    ScriptArguments: '-resourceName $(resourceName)'
    errorActionPreference: continue
    azurePowerShellVersion: LatestVersion
    workingDirectory: '$(System.DefaultWorkingDirectory)'

- task: PowerShell@2
  displayName: 'Generate name app service'
  inputs:
    targetType: filePath
    filePath: '$(System.DefaultWorkingDirectory)/_Swagger-CI-JeraldinneMolleda/AzureTestProject/scripts/generateName.ps1'
    arguments: '-Location "West US" -ResourceType "App Service" -Environment "DEV"'
    workingDirectory: '$(System.DefaultWorkingDirectory)'

- task: AzurePowerShell@5
  displayName: 'Deploy resource app service'
  inputs:
    azureSubscription: 'Azure Subscription Academy'
    ScriptPath: '$(System.DefaultWorkingDirectory)/_Swagger-CI-JeraldinneMolleda/AzureTestProject/scripts/createResourceAzure.ps1'
    ScriptArguments: '-resourceName $(resourceName)'
    errorActionPreference: continue
    azurePowerShellVersion: LatestVersion
    workingDirectory: '$(System.DefaultWorkingDirectory)'

- task: PowerShell@2
  displayName: 'Generate name app insights'
  inputs:
    targetType: filePath
    filePath: '$(System.DefaultWorkingDirectory)//_Swagger-CI-JeraldinneMolleda/AzureTestProject/scripts/generateName.ps1'
    arguments: '-Location "East US" -ResourceType "Application Insights" -Environment "DEV"'
    workingDirectory: '$(System.DefaultWorkingDirectory)'

- task: AzurePowerShell@5
  displayName: 'Deploy resource application insights'
  inputs:
    azureSubscription: 'Azure Subscription Academy'
    ScriptPath: '$(System.DefaultWorkingDirectory)/_Swagger-CI-JeraldinneMolleda/AzureTestProject/scripts/createResourceAzure.ps1'
    ScriptArguments: '-resourceName $(resourceName)'
    errorActionPreference: continue
    azurePowerShellVersion: LatestVersion
    workingDirectory: '$(System.DefaultWorkingDirectory)'

- task: AzureRmWebAppDeployment@4
  displayName: 'Azure App Service Deploy: $(webAppName)'
  inputs:
    azureSubscription: 'Azure Subscription Academy'
    WebAppName: '$(webAppName)'
    packageForLinux: '$(System.DefaultWorkingDirectory)/_Swagger-CI-JeraldinneMolleda/AzureTestProject/RoundTheCode.AzureTestProject.zip'
    enableCustomDeployment: true
    DeploymentType: zipDeploy
