# Trigger #
trigger: 
- none

# Pool #
pool: 
  vmImage: windows-2019

# Resources #
resources:
  pipelines: 
  - pipeline: Swagger-CI-JeraldinneMolleda
    project: CT Engineering School
    source: Swagger-CI-JeraldinneMolleda


# Stages #
stages: 
- template: ../../Templates/Stages/Development.yaml
- template: ../../Templates/Stages/QA.yaml
- template: ../../Templates/Stages/UAT.yaml
- template: ../../Templates/Stages/Production.yaml